### ISSUE TITLE
undefined method `respond_with' for RSpec

### ISSUE THREAD

**Issue by dwaynemac** [nviennot/irb-config#34]
My specs are all green when running

```
rspec spec
```

But when running through irb-console I get several:

```
undefined method `respond_with' for RSpec
```

¿Any hints?

Here's my Gemfile.lock

GEM
  remote: http://rubygems.org/
  specs:
    accounts_client (0.0.20)
      gravtastic
      logical_model (~> 0.5.8)
      railties (>= 3.1)
    actionmailer (3.1.6)
      actionpack (= 3.1.6)
      mail (~> 2.3.3)
    actionpack (3.1.6)
      activemodel (= 3.1.6)
      activesupport (= 3.1.6)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      i18n (~> 0.6)
      rack (~> 1.3.6)
      rack-cache (~> 1.2)
      rack-mount (~> 0.8.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.0.4)
    activemodel (3.1.6)
      activesupport (= 3.1.6)
      builder (~> 3.0.0)
      i18n (~> 0.6)
    activerecord (3.1.6)
      activemodel (= 3.1.6)
      activesupport (= 3.1.6)
      arel (~> 2.2.3)
      tzinfo (~> 0.3.29)
    activeresource (3.1.6)
      activemodel (= 3.1.6)
      activesupport (= 3.1.6)
    activesupport (3.1.6)
      multi_json (>= 1.0, < 1.3)
    activity_stream_client (0.0.14)
      logical_model (~> 0.5.0)
      railties (>= 3.1)
    appsignal (0.8.7)
      activesupport (>= 3.0)
      rack
      thread_safe
    appsignal-mongo (0.1.10)
      appsignal (> 0.7)
      mongo
    arel (2.2.3)
    atomic (1.1.15)
    bson (1.4.0)
    bson_ext (1.4.0)
    builder (3.0.4)
    cancan (1.6.10)
    capybara (2.2.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    carrierwave (0.5.8)
      activesupport (~> 3.0)
    carrierwave-mongoid (0.1.7)
      carrierwave (~> 0.5.6)
      mongoid (~> 2.1)
    childprocess (0.3.9)
      ffi (~> 1.0, >= 1.0.11)
    coderay (1.1.0)
    colorize (0.6.0)
    columnize (0.3.6)
    coveralls (0.5.8)
      colorize
      json
      rest-client
      simplecov (>= 0.7)
      thor
    crack (0.4.1)
      safe_yaml (~> 0.9.0)
    cucumber (1.2.1)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.11.0)
      json (>= 1.4.6)
    cucumber-rails (1.2.0)
      capybara (>= 1.1.1)
      cucumber (>= 1.1.1)
      nokogiri (>= 1.5.0)
    daemons (1.1.9)
    dalli (2.6.4)
    database_cleaner (1.2.0)
    debugger (1.6.4)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.2.0)
      debugger-ruby_core_source (~> 1.3.0)
    debugger-linecache (1.2.0)
    debugger-ruby_core_source (1.3.0)
    delayed_job (3.0.5)
      activesupport (~> 3.0)
    delayed_job_mongoid (1.0.8)
      delayed_job (~> 3.0.0)
      mongoid (>= 2.0)
    diff-lcs (1.2.5)
    docile (1.1.1)
    erubis (2.7.0)
    ethon (0.4.2)
      ffi (~> 1.0.11)
      mime-types (~> 1.18)
    excon (0.31.0)
    faker (0.9.4)
      i18n (~> 0.4)
    fast-stemmer (1.0.2)
    ffi (1.0.11)
    figaro (0.7.0)
      bundler (~> 1.0)
      rails (>= 3, < 5)
    fog (1.19.0)
      builder
      excon (~> 0.31.0)
      formatador (~> 0.2.0)
      mime-types
      multi_json (~> 1.0)
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
      nokogiri (~> 1.5)
      ruby-hmac
    formatador (0.2.4)
    gherkin (2.11.6)
      json (>= 1.7.6)
    git-pivotal-tracker-integration (1.4.0)
      highline (~> 1.6)
      pivotal-tracker (~> 0.5)
    gravtastic (3.2.6)
    guard (1.8.3)
      formatador (>= 0.2.4)
      listen (~> 1.3)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-rspec (3.1.0)
      guard (>= 1.8)
      rspec (~> 2.13)
    guard-spork (1.5.1)
      childprocess (>= 0.2.3)
      guard (>= 1.1)
      spork (>= 0.8.4)
    happymapper (0.4.1)
      libxml-ruby (~> 2.0)
    heroku-mongo-backup (0.4.32)
      mongo
    highline (1.6.20)
    hike (1.2.3)
    i18n (0.6.9)
    json (1.8.1)
    kaminari (0.13.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
      railties (>= 3.0.0)
    kgio (2.8.1)
    libnotify (0.8.2)
      ffi (>= 1.0.11)
    libxml-ruby (2.7.0)
    listen (1.3.1)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      rb-kqueue (>= 0.2)
    logical_model (0.5.10)
      activemodel
      activesupport
      ethon (= 0.4.2)
      kaminari (~> 0.13.0)
      typhoeus (= 0.5.0.alpha)
    lumberjack (1.0.4)
    machinist (1.0.6)
    machinist_mongo (1.2.0)
      machinist (~> 1.0.6)
    mail (2.3.3)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    memcachier (0.0.2)
    messaging_client (0.0.3)
      logical_model (~> 0.5.0)
      railties (>= 3.1)
    method_source (0.8.2)
    mime-types (1.25.1)
    mini_portile (0.5.2)
    mongo (1.4.0)
      bson (= 1.4.0)
    mongoid (2.3.3)
      activemodel (~> 3.1)
      mongo (~> 1.3)
      tzinfo (~> 0.3.22)
    mongoid-rspec (1.4.4)
      mongoid (~> 2.0)
      rspec (~> 2)
    mongoid_search (0.2.8)
      bson_ext (>= 1.2)
      fast-stemmer (~> 1.0.0)
      mongoid (>= 2.0.0)
    multi_json (1.2.0)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.7.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    nokogiri-happymapper (0.5.8)
      nokogiri (~> 1.5)
    overmind_client (0.0.5)
      logical_model (~> 0.5.0)
      railties (>= 3.1)
    padma-deployment (0.0.1)
      railties (>= 3.1)
    pivotal-tracker (0.5.12)
      builder
      builder
      crack
      happymapper (>= 0.3.2)
      nokogiri (>= 1.4.3)
      nokogiri (>= 1.5.5)
      nokogiri-happymapper (>= 0.5.4)
      rest-client (~> 1.6.0)
      rest-client (~> 1.6.0)
    polyglot (0.3.3)
    pry (0.9.12.4)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rack (1.3.10)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-mount (0.8.3)
      rack (>= 1.0.0)
    rack-ssl (1.3.3)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.1.6)
      actionmailer (= 3.1.6)
      actionpack (= 3.1.6)
      activerecord (= 3.1.6)
      activeresource (= 3.1.6)
      activesupport (= 3.1.6)
      bundler (~> 1.0)
      railties (= 3.1.6)
    railties (3.1.6)
      actionpack (= 3.1.6)
      activesupport (= 3.1.6)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (~> 0.14.6)
    raindrops (0.12.0)
    rake (10.1.1)
    rb-fsevent (0.9.3)
    rb-inotify (0.9.3)
      ffi (>= 0.5.0)
    rb-kqueue (0.2.0)
      ffi (>= 0.5.0)
    rdoc (3.12.2)
      json (~> 1.4)
    redcarpet (3.0.0)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rmagick (2.13.2)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.7)
    rspec-expectations (2.14.4)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.4)
    rspec-rails (2.14.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    ruby-hmac (0.4.0)
    ruby-mass (0.1.3)
    safe_yaml (0.9.7)
    shoulda-matchers (2.4.0)
      activesupport (>= 3.0.0)
    simplecov (0.8.2)
      docile (~> 1.1.0)
      multi_json
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    slop (3.4.7)
    spork (1.0.0rc4)
    sprockets (2.0.4)
      hike (~> 1.2)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    state_machine (1.1.2)
    thor (0.14.6)
    thread_safe (0.2.0)
      atomic (>= 1.1.7, < 2)
    tilt (1.4.1)
    timecop (0.3.5)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    typhoeus (0.5.0.alpha)
      ethon (~> 0.4.2)
    tzinfo (0.3.38)
    unf (0.1.3)
      unf_ext
    unf_ext (0.0.6)
    unicorn (4.7.0)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    xpath (2.0.0)
      nokogiri (~> 1.3)
    yard (0.8.7.3)
    yard-restful (1.2.2)
      yard (~> 0.8.3)

PLATFORMS
  ruby

DEPENDENCIES
  accounts_client (~> 0.0.18)
  activity_stream_client (~> 0.0.14)
  appsignal
  appsignal-mongo
  bson (= 1.4.0)
  bson_ext (= 1.4.0)
  cancan (~> 1.6.7)
  carrierwave
  carrierwave-mongoid
  coveralls
  cucumber-rails (= 1.2.0)
  daemons
  dalli
  database_cleaner (>= 0.6.7)
  debugger
  delayed_job_mongoid
  ethon (= 0.4.2)
  faker (= 0.9.4)
  figaro
  fog
  git-pivotal-tracker-integration
  guard-rspec
  guard-spork
  heroku-mongo-backup (~> 0.4.3)
  i18n (~> 0.6.6)
  kaminari (~> 0.13)
  libnotify
  logical_model (~> 0.5.8)
  machinist (= 1.0.6)
  machinist_mongo (= 1.2.0)
  memcachier
  messaging_client
  mongoid (= 2.3.3)
  mongoid-rspec (= 1.4.4)
  mongoid_search
  overmind_client (~> 0.0.1)
  padma-deployment
  rails (= 3.1.6)
  rake
  rb-inotify
  redcarpet
  rmagick
  rspec-rails (~> 2.14)
  ruby-mass
  shoulda-matchers
  spork (> 0.9.0.rc)
  state_machine (~> 1.1.2)
  timecop (= 0.3.5)
  unf
  unicorn
  yard (~> 0.8.3)
  yard-restful

**Comment by artdias90** [comment]
Solved by adding this to spec_helper.rb

'Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.library :rails
  end
end'
