### ISSUE TITLE
Unable to install irb-config with rbnev

### ISSUE THREAD

**Issue by arasevic** [nviennot/irb-config#41]
I am trying to stall irb-config. I cloned it per the directions in the README.md file and changed into the ~/.irb directory. When I run "make" I get the following error:
Makefile:14: *** Please use rvm or rbenv.  Stop.
I isntalled rbenv via homebrew and when I run rbenv --version I get the following output:
rbenv 0.4.0 which is the most current stable release. 
I am really excited about using irb-config. What should I do to fix this problem?

**Comment by nviennot** [comment]
Fixed :)

**Comment by arasevic** [comment]
Thanks! If I'm getting errors regarding being unable to uninstall specific gems because they are not listed in GEM_HOME should I worry about those messages?

**Comment by nviennot** [comment]
I don't know

**Comment by arasevic** [comment]
Ok. I appreciate you getting back to me
